### ISSUE TITLE
Error in read_generic_cols() with graphviper.utils.logger

### ISSUE THREAD

**Issue by FedeMPouzols** [casangi/xradio#132]
When loading troublesome colums that produce read errors (such as SPECTRAL_WINDOW/ASSOC_NATURE) a warning/debug message is printed with different level depending on whether the issue happens for a "known troublesome" column or an unexpected column. This got broken after PR #119. Test datasets can produce errors like:
```
File "/home/fedemp/ws_xradio_pointing/venv_xradio_python_38/lib/python3.8/site-packages/xradio/vis/_vis_utils/_ms/_tables/read.py", line 349, in read_generic_table
    mcoords, mvars = read_generic_cols(infile, tb_tool, timecols, ignore)
  File "/home/fedemp/ws_xradio_pointing/venv_xradio_python_38/lib/python3.8/site-packages/xradio/vis/_vis_utils/_ms/_tables/read.py", line 469, in read_generic_cols
    level = logger.WARNING
AttributeError: module 'graphviper.utils.logger' has no attribute 'WARNING'
```

A simple fix could be:
```
diff --git a/src/xradio/vis/_vis_utils/_ms/_tables/read.py b/src/xradio/vis/_vis_utils/_ms/_tables/read.py
index 71a1aac..4f7c321 100644
--- a/src/xradio/vis/_vis_utils/_ms/_tables/read.py
+++ b/src/xradio/vis/_vis_utils/_ms/_tables/read.py
@@ -464,12 +466,11 @@ def read_generic_cols(
                     ]
                 )
             except Exception as exc:
-                level = logger.WARNING
+                msg = f"{infile}: failed to read data for column {col}: {exc}"
                 if col in known_misbehaving_cols:
-                    level = logger.DEBUG
-                logger.log(
-                    level, f"{infile}: failed to read data for column {col}: {exc}"
-                )
+                    logger.debug(msg)
+                else:
+                    logger.warning(msg)
                 data = []
 
         if len(data) == 0:
```

@jrhosk: is there any plan to have these logger.log(), logger.WARNING, logger.INFO, etc. in graphviper.utils.logger, or its interface will stay simpler than Python's logging?

**Comment by jrhosk** [comment]
Maybe I am misunderstanding but warning is there as logger.warning()

**Comment by jrhosk** [comment]
I see what you are asking for I think. I hadn't imagined it being used that way, e.g. having conditional messages based on the logging level. I can add those features if it is important to have. I had thought messages would just be classified as warning (), error(), ect without having a condition.

**Comment by jrhosk** [comment]
Alright, I understand. It can be added, yes. I'll plan on working on it in a few weeks when I get some things off my plate. Thanks for pointing it out.

**Comment by jrhosk** [comment]
@FedeMPouzols You can assign this to me if you would like. I'll fix it in the next week or so.

**Comment by jrhosk** [comment]
@FedeMPouzols I have added the `logger.log()` and `logger.exception()` options to the `graphviper` logger. They should be in the main branch as soon as JW reviews the changes. The logger keywords are already there since the graphviper logger is just a wrapper on the logging module, a logger instance doesn't give access to those keywords anyway you have to use `logging.WARNING`; I am guessing the original code must have done something like `import logging as logger` The bugged code just needs to have logger.WARNING changed to logging.WARNING. I have added all the keyword in now though so `logger.WARNING` for instance should work. Do you want me to implement the change?

**Comment by FedeMPouzols** [comment]
This is no longer an issue. Josh added more functions as explained in the comment above and the code has changed since then.
